### ISSUE TITLE
Define config format

### ISSUE THREAD

**Issue by pgdr** [Statoil/camille#4]
e.g.
```yml
tag: [*nacelle*, *lidar*]
start: 2016-08-09
end: 2016-08-09
processor: lidar_correction
join: left
interpolation: nearest
resampling: ?
```
